version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - ./src:/app/src
    entrypoint: ["dumb-init", "--"]
    command: ["./main"]